#!/usr/bin/env python3
"""
Convert any Python script into a self-contained Google Colab Jupyter Notebook (.ipynb).
Adds Open in Colab badges, GPU diagnostics, pip dependency cells, and interactive form headers.
"""

import sys
import os
import json
import argparse


def convert_py_to_colab(py_file_path: str, output_ipynb_path: str = None, repo_slug: str = None):
    if not os.path.exists(py_file_path):
        print(f"Error: File not found: {py_file_path}")
        return

    with open(py_file_path, "r", encoding="utf-8") as f:
        code_content = f.read()

    base_name = os.path.splitext(os.path.basename(py_file_path))[0]
    out_path = output_ipynb_path or f"{base_name}_colab.ipynb"

    # Badges
    badge_md = f"# {base_name.replace('_', ' ').title()}\n\n"
    if repo_slug:
        badge_md += f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/{repo_slug}/blob/main/{os.path.basename(out_path)})\n\n"
    badge_md += "Interactive Google Colab notebook generated by **Antigravity Google Colab Skill**.\n"

    # GPU preflight
    gpu_check_code = """# @title 1. Hardware & GPU Acceleration Diagnostic
import torch
print(f"CUDA Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Active GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Running on CPU runtime (Go to Runtime -> Change runtime type -> T4 GPU if needed)")
"""

    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [line + "\n" for line in badge_md.splitlines()]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [line + "\n" for line in gpu_check_code.splitlines()]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [line + "\n" for line in code_content.splitlines()]
        }
    ]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 0,
        "metadata": {
            "colab": {
                "provenance": []
            },
            "kernelspec": {
                "name": "python3",
                "display_name": "Python 3"
            },
            "language_info": {
                "name": "python"
            },
            "accelerator": "GPU"
        },
        "cells": cells
    }

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)

    print(f"✅ Converted {py_file_path} -> Colab Notebook: {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert Python script to Google Colab Notebook")
    parser.add_argument("file", help="Python source file path")
    parser.add_argument("--out", default=None, help="Output .ipynb path")
    parser.add_argument("--repo", default=None, help="GitHub repo slug (e.g. username/repo) for Colab badge link")
    args = parser.parse_args()

    convert_py_to_colab(args.file, args.out, args.repo)
