"""
Test Forge Engine.
Parses Python source, inventories callables and branches, and generates
runnable pytest skeleton tests with a projected-coverage gap analysis.
"""

import re
from dataclasses import dataclass, field
from typing import List

@dataclass
class CallableSpec:
    name: str
    kind: str          # function | method | class
    args: List[str]
    branches: int
    is_public: bool

@dataclass
class TestCase:
    target: str
    scenario: str      # happy | edge | failure
    body_comment: str

@dataclass
class ForgePlan:
    callables: List[CallableSpec]
    total_branches: int
    tests: List[TestCase] = field(default_factory=list)
    projected_coverage: float = 0.0
    uncovered_branches: List[str] = field(default_factory=list)
    test_code: str = ""
    verdict: str = "GAPS_REMAIN"

class TestForgeEngine:
    """Test generation with honest branch accounting — no fake 100% promises."""

    BRANCH_TOKENS = ("if", "elif", "for", "while", "except", "case", "and", "or")

    @classmethod
    def forge(cls, source: str, target_coverage: int = 80) -> ForgePlan:
        callables: List[CallableSpec] = []
        current = None
        branch_count = 0
        for line in source.splitlines():
            m = re.match(r"\s*def\s+(\w+)\s*\(([^)]*)\)", line)
            cm = re.match(r"\s*class\s+(\w+)", line)
            if m:
                name, argstr = m.group(1), m.group(2)
                args = [a.split(":")[0].split("=")[0].strip() for a in argstr.split(",") if a.strip()]
                args = [a for a in args if a not in ("self", "cls", "*args", "**kwargs")]
                current = CallableSpec(name, "function", args, 0, not name.startswith("_"))
                callables.append(current)
                branch_count = 0
                continue
            if cm:
                current = CallableSpec(cm.group(1), "class", [], 0, not cm.group(1).startswith("_"))
                callables.append(current)
                branch_count = 0
                continue
            if current is not None:
                if any(re.search(rf"^\s*(el)?{tok}\b|^\s*{tok}\b", line) or re.search(rf"\b(and|or)\b", line)
                       for tok in cls.BRANCH_TOKENS):
                    branch_count += 1
                    current.branches = branch_count

        public = [c for c in callables if c.kind == "function" and c.is_public] or callables
        tests: List[TestCase] = []
        for spec in public:
            if spec.kind != "function":
                continue
            arg_preview = ", ".join(spec.args[:3]) if spec.args else ""
            tests.append(TestCase(spec.name, "happy",
                                  f"call {spec.name}({arg_preview}) with representative input; assert a sane result type."))
            if spec.args:
                tests.append(TestCase(spec.name, "edge",
                                      f"call {spec.name} with empty/None/zero values for {', '.join(spec.args[:2])}; assert graceful handling."))
            tests.append(TestCase(spec.name, "failure",
                                  f"call {spec.name} with invalid input; assert the documented exception or fallback."))
            for b in range(max(spec.branches - 3, 0)):
                tests.append(TestCase(spec.name, "branch",
                                      f"exercise untaken branch #{b + 1} of {spec.name} (drive the condition both ways)."))

        total_branches = sum(c.branches for c in callables if c.kind == "function")
        covered_est = min(len([t for t in tests if t.scenario != "failure"]) * 1.0, total_branches)
        projected = round(100 * covered_est / total_branches, 1) if total_branches else 100.0
        uncovered = [f"{c.name}: {max(c.branches - 3, 0)} branch(es) beyond generated cases"
                     for c in callables if c.kind == "function" and c.branches > 3]

        code_lines = ['"""Generated by Test Forge Agent — edit fixtures to fit your domain."""',
                      "import pytest", ""]
        for t in tests:
            code_lines += [f"def test_{t.target}_{t.scenario}():",
                           f"    # {t.body_comment}",
                           "    pytest.skip('forge: wire real fixtures')", ""]

        verdict = "TARGET_MET" if projected >= target_coverage else "GAPS_REMAIN"
        return ForgePlan(callables=callables, total_branches=total_branches, tests=tests,
                         projected_coverage=projected, uncovered_branches=uncovered,
                         test_code="\n".join(code_lines), verdict=verdict)

    @staticmethod
    def format_plan(plan: ForgePlan) -> str:
        out = ["=" * 62, "TEST FORGE AGENT — PLAN", "=" * 62,
               f"Callables found: {len(plan.callables)} | total branches: {plan.total_branches}",
               f"Tests generated: {len(plan.tests)} | projected coverage: {plan.projected_coverage}%",
               "-" * 62, "Callable inventory:"]
        for c in plan.callables[:15]:
            out.append(f"  {c.kind:8} {c.name}({', '.join(c.args)}) branches={c.branches} public={c.is_public}")
        if len(plan.callables) > 15:
            out.append(f"  ... and {len(plan.callables) - 15} more")
        out += ["-" * 62, "Test scenarios:"]
        for t in plan.tests[:12]:
            out.append(f"  [{t.scenario:7}] test_{t.target}_{t.scenario}")
        if len(plan.tests) > 12:
            out.append(f"  ... and {len(plan.tests) - 12} more")
        if plan.uncovered_branches:
            out += ["-" * 62, "Uncovered branches (manual attention):"]
            out += [f"  - {u}" for u in plan.uncovered_branches]
        out += ["-" * 62, f"VERDICT: {plan.verdict} (target coverage reached: "
                 f"{'yes' if plan.verdict == 'TARGET_MET' else 'no'})",
                 "Scaffold (first 30 lines):"]
        out += ["  " + ln for ln in plan.test_code.splitlines()[:30]]
        out.append("=" * 62)
        return "\n".join(out)
