"""
Access Review Agent Engine.
Audits access grants for least-privilege violations: dormant access,
wildcard permissions, privilege clusters, MFA gaps — with a ranked
revocation list and SOC2-style evidence summary.
"""

from dataclasses import dataclass, field
from typing import List

@dataclass
class UserRisk:
    user: str
    risk_score: float
    violations: List[str] = field(default_factory=list)
    grants_to_revoke: List[str] = field(default_factory=list)

@dataclass
class AccessReport:
    total_grants: int
    total_users: int
    users_at_risk: List[UserRisk] = field(default_factory=list)
    global_findings: List[str] = field(default_factory=list)
    revocation_list: List[str] = field(default_factory=list)
    evidence_bundle: List[str] = field(default_factory=list)
    verdict: str = ""

ADMIN_MARKERS = {"admin", "root", "superuser", "owner", "*", "full_access", "write_all"}
CRITICAL_RESOURCES = {"production", "prod", "payments", "billing", "secrets", "iam", "database", "customer_data"}

class AccessReviewEngine:
    """Access is a liability that expires — review it before an auditor, or an attacker, does."""

    @classmethod
    def review(cls, grants: List[dict]) -> AccessReport:
        if not grants:
            return AccessReport(0, 0, [], ["No grants provided."], [],
                                ["Run the IAM collector first."], "NO_DATA")

        users = {}
        total = len(grants)
        admin_total = 0
        no_mfa = set()

        for g in grants:
            user = str(g.get("user", g.get("principal", "?")))
            role = str(g.get("role", g.get("permission", "read")).lower())
            resource = str(g.get("resource", "unknown")).lower()
            last_used = g.get("last_used_days", g.get("days_since_use", 0))
            try:
                last_used = float(last_used)
            except (TypeError, ValueError):
                last_used = 0.0
            mfa = bool(g.get("mfa", True))

            users.setdefault(user, {"grants": [], "violations": [], "score": 0.0,
                                    "revoke": [], "admin": False})
            u = users[user]
            u["grants"].append((role, resource, last_used))
            if not mfa:
                no_mfa.add(user)
                u["violations"].append("account has MFA disabled")

            is_admin = any(m in role for m in ADMIN_MARKERS) or role == "*"
            is_critical = any(c in resource for c in CRITICAL_RESOURCES)

            if is_admin:
                admin_total += 1
                u["admin"] = True
                u["score"] += 6
                u["violations"].append(f"admin-level role '{role}' on {resource}")
            if last_used > 90:
                u["score"] += 10
                u["violations"].append(f"grant unused for {last_used:.0f} days ({role} on {resource})")
                u["revoke"].append(f"{role}@{resource} (unused {last_used:.0f}d)")
            elif last_used > 45 and is_critical:
                u["score"] += 4
                u["violations"].append(f"critical-resource grant barely used ({last_used:.0f}d): {resource}")
            if is_admin and is_critical and last_used > 30:
                u["score"] += 8
                u["violations"].append(f"admin on critical resource {resource}, last used {last_used:.0f}d — highest-risk shape")
            if is_critical and not is_admin and last_used == 0:
                u["score"] += 2
                u["violations"].append(f"never-used access to critical {resource}")

        user_risks = []
        for user, u in users.items():
            if u["score"] > 0:
                user_risks.append(UserRisk(user, u["score"], u["violations"], u["revoke"]))
        user_risks.sort(key=lambda x: -x.risk_score)

        admin_pct = 100 * admin_total / max(1, total)
        findings = []
        if admin_pct > 15:
            findings.append(f"Admin-shaped grants are {admin_pct:.0f}% of all grants — least-privilege is aspirational here.")
        if no_mfa:
            findings.append(f"{len(no_mfa)} account(s) without MFA — fix before any revocation; it's the cheapest win.")
        dormant = sum(1 for x in user_risks if any("unused" in v for v in x.violations))
        if dormant:
            findings.append(f"{dormant} user(s) hold dormant grants (>90d unused) — dormant privilege is pre-staged attacker access.")
        if not findings:
            findings.append("No systemic least-privilege violations — tighten review cadence and move on.")

        revocations = []
        for ur in user_risks:
            for rvk in ur.grants_to_revoke:
                revocations.append(f"{ur.user}: revoke {rvk}")
        revocations = revocations[:15]

        evidence = [
            f"Review scope: {total} grants across {len(users)} users (generated by access-review-agent).",
            "Each revocation lists user, grant, and dormancy evidence — attach the query output as the artifact.",
            "Retain: this report + executed revocations + exceptions with business justification + expiry dates.",
            "Exceptions require: named approver, business reason, and a hard expiry (max 90 days) — no permanent exceptions.",
        ]

        verdict = (f"{total} grants | {len(users)} users | {len(user_risks)} at-risk | "
                   f"admin share {admin_pct:.0f}% | {len(revocations)} revocations proposed")
        return AccessReport(total, len(users), user_risks[:10], findings, revocations,
                            evidence, verdict)

    @staticmethod
    def format_report(r: AccessReport) -> str:
        out = ["=" * 62, "ACCESS REVIEW AGENT — REPORT", "=" * 62, r.verdict, "-" * 62,
               "Global findings:"]
        out += [f"  ! {f}" for f in r.global_findings]
        if r.users_at_risk:
            out += ["-" * 62, "Users ranked by risk:"]
            for u in r.users_at_risk:
                out.append(f"  {u.user:24} risk {u.risk_score:.0f}")
                out += [f"      - {v}" for v in u.violations[:4]]
        if r.revocation_list:
            out += ["-" * 62, "Revocation list (evidence-backed):"]
            out += [f"  [ ] {rv}" for rv in r.revocation_list]
        out += ["-" * 62, "Audit evidence bundle (SOC2/ISO-style):"]
        out += [f"  * {e}" for e in r.evidence_bundle]
        out += ["=" * 62, "Cadence: quarterly full review; monthly for critical resources; instant on role-change events."]
        return "\n".join(out)
